DROP TABLE IF EXISTS RESPUESTA;
DROP TABLE IF EXISTS ENCUESTA;
DROP TABLE IF EXISTS USUARIO;

CREATE TABLE USUARIO (
    uuid CHAR(36) PRIMARY KEY,
    nombre VARCHAR(63) NOT NULL,
    contrasegna VARCHAR(128) NOT NULL,
    fechaCreado TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    esAdmin CHAR(1),
    CONSTRAINT chk_esAdmin CHECK (esAdmin IN ('s','n'))

);

CREATE TABLE ENCUESTA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(127),
    contenido VARCHAR(1023),
    uuid_USUARIO CHAR(36),
    uuidsPermisos VARCHAR(1023),
    tipoPermisos CHAR(1), 
    CONSTRAINT fk_ENCUESTA_uuid_USUARIO FOREIGN KEY (uuid_USUARIO) REFERENCES USUARIO(uuid),
    CONSTRAINT chk_tipoPermisos CHECK (tipoPermisos IN ('b','n','w')),
    foto VARCHAR(127)
);

CREATE TABLE RESPUESTA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    contenido VARCHAR(4095),
    uuid_USUARIO CHAR(36),
    id_ENCUESTA INT,
    CONSTRAINT fk_RESPUESTA_uuid_USUARIO FOREIGN KEY (uuid_USUARIO) REFERENCES USUARIO(uuid),
    CONSTRAINT fk_RESPUESTA_id_ENCUESTA FOREIGN KEY (id_ENCUESTA) REFERENCES ENCUESTA(id)
);

ALTER TABLE USUARIO AUTO_INCREMENT = 1;
ALTER TABLE ENCUESTA AUTO_INCREMENT = 1;
ALTER TABLE RESPUESTA AUTO_INCREMENT = 1;
